spring: 
  profiles: 
    active:
    - dev
---
server:
  port: 7002

spring:
  profiles: dev
  application: 
    name: microservicecloud-config-eureka-client
    
eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false    #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false          #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
---
server:
  port: 7002

spring:
  profiles: test
  application: 
    name: microservicecloud-config-eureka-client
    
eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false    #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false          #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/